/**
 * Provenance Export
 *
 * For each finalist candidate, exports:
 * - CIF file (standard crystallographic format)
 * - POSCAR file (VASP format for DFT reproducibility)
 * - Provenance JSON (full generation → DFT → phonon trail)
 * - QE input summary
 *
 * This makes results traceable and reproducible.
 */

import * as fs from "fs";
import * as path from "path";
import type { CSPCandidate } from "./csp-types";
import { writePOSCAR, latticeParamsToVectors } from "./poscar-io";

export interface ProvenanceRecord {
  candidateId: string;
  formula: string;
  composition: Record<string, number>;
  pressureGPa: number;

  // Generation
  generator: string;
  generationSeed: number;
  zFormulaUnits: number | null;
  volumeMultiplier: number | null;
  spaceGroup: string;
  parentSeeds: number[];

  // Funnel
  funnelTier: string;
  funnelStagesSurvived: string[];
  clusterId: string | null;
  clusterSize: number | null;
  selectionCategory: string;

  // DFT
  dft0Rank: number | null;
  dftQualityTier: string;
  scfEnergy: number | null;
  scfEnthalpy: number | null;
  scfFermiEnergy: number | null;
  scfBandGap: number | null;
  scfConverged: boolean;
  relaxedLatticeA: number | null;

  // Phonon
  phononStable: boolean | null;
  phononLowestFreq: number | null;
  phononOmegaLog: number | null;

  // Tc
  tcEstimate: number | null;
  lambdaEPC: number | null;

  // Timestamps
  generatedAt: string;
  dftCompletedAt: string | null;
}

/**
 * Write CIF file for a candidate structure.
 */
export function writeCIF(
  candidate: CSPCandidate,
  formula: string,
  outputPath: string,
): void {
  const a = candidate.latticeA;
  const b = candidate.latticeB ?? a;
  const c = candidate.latticeC ?? a * (candidate.cOverA ?? 1.0);
  const alpha = candidate.latticeParams?.alpha ?? 90;
  const beta = candidate.latticeParams?.beta ?? 90;
  const gamma = candidate.latticeParams?.gamma ??
    (candidate.crystalSystem === "hexagonal" ? 120 : 90);

  let cif = `# CIF generated by Quantum Alchemy Engine\n`;
  cif += `# Formula: ${formula}\n`;
  cif += `# Source: ${candidate.source ?? candidate.prototype ?? "unknown"}\n`;
  cif += `# Pressure: ${candidate.pressureGPa ?? 0} GPa\n\n`;
  cif += `data_${formula.replace(/[^a-zA-Z0-9]/g, "_")}\n\n`;
  cif += `_cell_length_a    ${a.toFixed(4)}\n`;
  cif += `_cell_length_b    ${b.toFixed(4)}\n`;
  cif += `_cell_length_c    ${c.toFixed(4)}\n`;
  cif += `_cell_angle_alpha ${alpha.toFixed(2)}\n`;
  cif += `_cell_angle_beta  ${beta.toFixed(2)}\n`;
  cif += `_cell_angle_gamma ${gamma.toFixed(2)}\n`;
  cif += `_symmetry_space_group_name_H-M '${candidate.spaceGroup || "P 1"}'\n\n`;
  cif += `loop_\n`;
  cif += `_atom_site_label\n`;
  cif += `_atom_site_type_symbol\n`;
  cif += `_atom_site_fract_x\n`;
  cif += `_atom_site_fract_y\n`;
  cif += `_atom_site_fract_z\n`;

  const elementCounts: Record<string, number> = {};
  for (const pos of candidate.positions) {
    elementCounts[pos.element] = (elementCounts[pos.element] ?? 0) + 1;
    const label = `${pos.element}${elementCounts[pos.element]}`;
    cif += `${label.padEnd(6)} ${pos.element.padEnd(4)} ${pos.x.toFixed(6)} ${pos.y.toFixed(6)} ${pos.z.toFixed(6)}\n`;
  }

  fs.writeFileSync(outputPath, cif);
}

/**
 * Export provenance package for a finalist candidate.
 */
export function exportProvenance(
  candidate: CSPCandidate,
  formula: string,
  outputDir: string,
  dftResult?: any,
): {
  cifPath: string;
  poscarPath: string;
  provenancePath: string;
} {
  fs.mkdirSync(outputDir, { recursive: true });

  // Write CIF
  const cifPath = path.join(outputDir, `${formula}.cif`);
  writeCIF(candidate, formula, cifPath);

  // Write POSCAR
  const poscarPath = path.join(outputDir, `${formula}.poscar`);
  fs.writeFileSync(poscarPath, writePOSCAR(candidate));

  // Build provenance record
  const zMatch = candidate.source?.match(/Z=(\d+)/);
  const volMatch = candidate.source?.match(/vol=([0-9.]+)/);

  const counts: Record<string, number> = {};
  for (const p of candidate.positions) {
    counts[p.element] = (counts[p.element] ?? 0) + 1;
  }

  const provenance: ProvenanceRecord = {
    candidateId: `${formula}_seed${candidate.seed}`,
    formula,
    composition: counts,
    pressureGPa: candidate.pressureGPa ?? 0,

    generator: candidate.prototype ?? candidate.sourceEngine ?? "unknown",
    generationSeed: candidate.seed,
    zFormulaUnits: zMatch ? parseInt(zMatch[1]) : null,
    volumeMultiplier: volMatch ? parseFloat(volMatch[1]) : null,
    spaceGroup: candidate.spaceGroup ?? "",
    parentSeeds: candidate.parentSeeds ?? [],

    funnelTier: "unknown",
    funnelStagesSurvived: candidate.relaxationHistory ?? [],
    clusterId: candidate.motifId ?? null,
    clusterSize: null,
    selectionCategory: "",

    dft0Rank: null,
    dftQualityTier: dftResult?.qualityTier ?? "unknown",
    scfEnergy: dftResult?.scf?.totalEnergy ?? null,
    scfEnthalpy: null,
    scfFermiEnergy: dftResult?.scf?.fermiEnergy ?? null,
    scfBandGap: dftResult?.scf?.bandGap ?? null,
    scfConverged: dftResult?.scf?.converged ?? false,
    relaxedLatticeA: dftResult?.relaxedLatticeA ?? null,

    phononStable: dftResult?.phonon ? !dftResult.phonon.hasImaginary : null,
    phononLowestFreq: dftResult?.phonon?.lowestFrequency ?? null,
    phononOmegaLog: dftResult?.phonon?.omegaLog ?? null,

    tcEstimate: null,
    lambdaEPC: null,

    generatedAt: new Date().toISOString(),
    dftCompletedAt: dftResult ? new Date().toISOString() : null,
  };

  const provenancePath = path.join(outputDir, `${formula}_provenance.json`);
  fs.writeFileSync(provenancePath, JSON.stringify(provenance, null, 2));

  console.log(`[Provenance] Exported ${formula}: ${cifPath}, ${poscarPath}, ${provenancePath}`);

  return { cifPath, poscarPath, provenancePath };
}
